# โอกาสในการเกิดมอนสเตอร์ตามระดับ
spawn-chance: 0.05
level-chances:
  low-level-chance: 60 # เปอร์เซ็นต์โอกาสในการเกิดมอนสเตอร์ระดับต่ำ (1-20)
  mid-level-chance: 35 # เปอร์เซ็นต์โอกาสในการเกิดมอนสเตอร์ระดับกลาง (21-35)
  high-level-chance: 5 # เปอร์เซ็นต์โอกาสในการเกิดมอนสเตอร์ระดับสูง (36-50)

min-level: 1 # ระดับต่ำสุดของมอนสเตอร์
max-level: 30 # ระดับสูงสุดของมอนสเตอร์

# มัลติพลายเออร์สำหรับค่าสุขภาพและความเสียหาย
health-multiplier-per-level: 2.0 # ค่าที่จะเพิ่มต่อระดับสำหรับสุขภาพ
damage-multiplier-per-level: 0.5 # ค่าที่จะเพิ่มต่อระดับสำหรับความเสียหาย

# ค่าความเร็วเริ่มต้น
base-speed: 0.3 # ความเร็วเริ่มต้นของมอนสเตอร์
speed-multiplier-per-level: 0.01 # ค่าที่จะเพิ่มต่อระดับสำหรับความเร็ว

# ค่าประสบการณ์เริ่มต้น
base-xp: 10.0 # ประสบการณ์ที่มอนสเตอร์จะมอบเมื่อถูกฆ่า
xp-multiplier-per-level: 2.0 # ค่าที่จะเพิ่มต่อระดับสำหรับประสบการณ์

# สีสำหรับแสดงระดับมอนสเตอร์
level-colors:
  low-level-color: "GREEN" # สีสำหรับระดับต่ำ (1-10)
  mid-level-color: "YELLOW" # สีสำหรับระดับกลาง (11-20)
  high-level-color: "GOLD" # สีสำหรับระดับสูง (21-30)
  extreme-level-color: "RED" # สีสำหรับระดับสุดขีด (30 ขึ้นไป)
